server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: localhost:8848