server:
  port: 8091
  tomcat:
    max-threads: 10  #tomcat的最大并发数修改为10，默认为200
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.201.52:13306/my_test?createDatabaseIfNotExist=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: EverSecHengAn123!@#
  jpa:
    show-sql: true # 默认false，在日志里显示执行的sql语句
    hibernate:
      ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会 新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
        #naming:
        #指定jpa的自动表生成策略，驼峰自动映射为下划线格式7
        #   implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        port: 9999 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 #指定sentinel控制台的服务地址
      filter:
        enabled: false #禁止收敛URL入口context，不然流控的链路控制不生效，SCA 2.1.2版本之后使用spring.cloud.sentinel.web-context-unify=false来关闭，之前需要自己写代码过滤器实现
  redis:
    database: 10
    host: 192.168.204.33
    port: 16379
    password: eversec123!@#
  zipkin:
    base-url: http://localhost:9411/ #zipkin server的请求地址
    discovery-client-enabled: false #让nacos把它当成一个url而不是一个服务
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比


# ribbon负载均衡策略
service-product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
feign:
  sentinel:
    enabled: true #开启fegin对sentinel的支持
# rocketmq配置
rocketmq:
  name-server: 192.168.201.52:9876
  producer:
    group: shop-order